[project]
name = "apitestingfwpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pylint>=4.0.9",
    "pytest>=9.1.1",
]
mock = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.54.0",
]

[tool.black]
line-length = 120
target-version = ["py313"]

[tool.pylint.messages_control]
disable = "C0114, R1711, W0621"
max-line-length = 120
